version: '3.3'
services:
  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    env_file: ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data


volumes:
  postgres_data:
  redis_data:
